[server]
port = 200 # 服务器端口

[command]
white_list = ["login", "lock", "cmd", "key", "volue"] # 服务器命令注册列表，列表外命令将无法使用

[authentication]
passkey = "H114514" # login登录使用的密码
max_try = 5 # login登录的最大尝试次数，为0则关闭（不推荐关闭）

